import { Column, CreateDateColumn, Entity, PrimaryColumn, UpdateDateColumn } from 'typeorm';

export type OrderStatus = 'PENDING' | 'CONFIRMED' | 'CANCELLED';

@Entity('orders')
export class Order {
  @PrimaryColumn()
  id: string;

  @Column()
  productId: string;

  @Column('integer')
  quantity: number;

  @Column('real')
  amount: number;

  @Column({ type: 'varchar' })
  status: OrderStatus;

  @Column({ type: 'varchar', nullable: true })
  failureReason: string | null;

  /** Generated by the client (e.g. a UUID when clicking "Buy"); reused on retries. */
  @Column({ unique: true })
  idempotencyKey: string;

  // With milliseconds, to correctly order orders created in the same second (bursts).
  @CreateDateColumn({ default: () => "STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')" })
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
